### ISSUE TITLE
[ANNOYANCE] add task button confusion.

### ISSUE THREAD

**Issue by Maestrofur** [DeliciousRaspberryPi/TaskTrackerIssues#9]
When I try to create a new item, my eye keeps being drawn to the plus sign button on the lower right corner of the screen. And every time I press that button, I get confused as to why it does not give me an option to add a task. I’m open to discussing possible solutions to this issue.

**Comment by DeliciousRaspberryPi** [comment]
Fixed in build 0.9.0+0
